/**
 * Generates supabase/seed.sql from the deterministic demo dataset so the
 * database and the offline demo mode contain identical listings.
 * Run: npx tsx scripts/generateSeed.ts
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { generateDemoListings } from '../src/data/demoListings'
import { DEMO_STATIONS, DEMO_STATION_EDGES } from '../src/data/demoStations'

const esc = (s: string) => s.replace(/'/g, "''")

const lines: string[] = [
  '-- Auto-generated by web/scripts/generateSeed.ts. Do not edit by hand.',
  '-- Fictional demo data (is_demo = true).',
  '',
]

for (const s of DEMO_STATIONS) {
  lines.push(
    `insert into public.stations (id, name, operator, line, latitude, longitude) values ('${s.id}', '${esc(s.name)}', '${esc(s.operator)}', '${esc(s.line)}', ${s.lat}, ${s.lng}) on conflict (id) do nothing;`,
  )
}
lines.push('')
for (const e of DEMO_STATION_EDGES) {
  lines.push(
    `insert into public.station_edges (from_station, to_station, minutes, line, is_transfer) values ('${e.from}', '${e.to}', ${e.minutes}, '${esc(e.line)}', ${e.transfer});`,
  )
}
lines.push('')
for (const l of generateDemoListings(80)) {
  lines.push(
    `insert into public.listings (external_id, title, description, property_name, address, prefecture, city, district, latitude, longitude, monthly_rent, management_fee, deposit, key_money, layout, floor_area, building_age, built_year, floor_number, total_floors, structure_type, nearest_station_name, walk_minutes_to_station, railway_line, image_urls, source_name, source_url, is_available, pets_allowed, furnished, bath_toilet_separate, auto_lock, delivery_box, parking_available, bicycle_parking, internet_free, air_conditioner, balcony, is_demo) values ('${esc(l.externalId)}', '${esc(l.title)}', '${esc(l.description)}', '${esc(l.propertyName)}', '${esc(l.address)}', '${esc(l.prefecture)}', '${esc(l.city)}', '${esc(l.district)}', ${l.lat}, ${l.lng}, ${l.monthlyRent}, ${l.managementFee}, ${l.deposit}, ${l.keyMoney}, '${esc(l.layout)}', ${l.floorArea}, ${l.buildingAge}, ${l.builtYear}, ${l.floorNumber}, ${l.totalFloors}, '${esc(l.structureType)}', '${esc(l.nearestStationName)}', ${l.walkMinutesToStation}, '${esc(l.railwayLine)}', '{}', '${esc(l.sourceName)}', '${esc(l.sourceUrl)}', ${l.isAvailable}, ${l.petsAllowed}, ${l.furnished}, ${l.bathToiletSeparate}, ${l.autoLock}, ${l.deliveryBox}, ${l.parkingAvailable}, ${l.bicycleParking}, ${l.internetFree}, ${l.airConditioner}, ${l.balcony}, true) on conflict (external_id) do nothing;`,
  )
}

const out = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../supabase/seed.sql',
)
writeFileSync(out, lines.join('\n') + '\n')
console.log(`wrote ${out}`)
